package com.inventory.common.template;

public enum BusinessDomain {
    CUSTOMER_MANAGEMENT,
    PRODUCT_MANAGEMENT,
    ORDER_PROCESSING,
    FINANCE_MANAGEMENT,
    INVENTORY_MANAGEMENT,
    SUPPLIER_MANAGEMENT,
    SALES_MANAGEMENT,
    PROCUREMENT_MANAGEMENT,
    REPORT_MANAGEMENT,
    SYSTEM_CONFIGURATION
}
