server:
  port: 8094

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:inventory_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:changeme}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

spring.cloud.nacos:
  discovery:
    server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
  config:
    server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}