const fs = require('fs');
const path = 'microservices/project-root/core-services/order-service/src/test/java/com/inventory/orderservice/service/impl/OrderServiceImplTest.java';
fs.appendFileSync(path, '\n');
fs.appendFileSync(path, '    @BeforeEach\n');
fs.appendFileSync(path, '    void setUp() {\n');
fs.appendFileSync(path, '        testOrderItems = new ArrayList<>();\n');
fs.appendFileSync(path, '        OrderItem item = new OrderItem();\n');
fs.appendFileSync(path, '        item.setId(1L);\n');
fs.appendFileSync(path, '        item.setProductId(100L);\n');
fs.appendFileSync(path, "        item.setProductName('Test Product');\n");
fs.appendFileSync(path, '        item.setQuantity(10);\n');
fs.appendFileSync(path, '        item.setUnitPrice(100.0);\n');
fs.appendFileSync(path, '        item.setCreatedAt(LocalDateTime.now());\n');
fs.appendFileSync(path, '        testOrderItems.add(item);\n');
fs.appendFileSync(path, '\n');
fs.appendFileSync(path, '        testOrder = new Order();\n');
fs.appendFileSync(path, '        testOrder.setId(1L);\n');
fs.appendFileSync(path, "        testOrder.setOrderNumber('ORD-2024-0001');\n");
fs.appendFileSync(path, "        testOrder.setCustomerName('Test Customer');\n");
fs.appendFileSync(path, '        testOrder.setStatus(Order.Status.PENDING);\n');
fs.appendFileSync(path, '        testOrder.setItems(testOrderItems);\n');
fs.appendFileSync(path, '        testOrder.setCreatedAt(LocalDateTime.now());\n');
fs.appendFileSync(path, '        testOrder.setUpdatedAt(LocalDateTime.now());\n');
fs.appendFileSync(path, '        testOrderItems.forEach(i -> i.setOrder(testOrder));\n');
fs.appendFileSync(path, '\n');
fs.appendFileSync(path, '        testOrderItemDTOs = new ArrayList<>();\n');
fs.appendFileSync(path, '        OrderItemDTO itemDTO = new OrderItemDTO();\n');
fs.appendFileSync(path, '        itemDTO.setProductId(100L);\n');
fs.appendFileSync(path, "        itemDTO.setProductName('Test Product');\n");
fs.appendFileSync(path, '        itemDTO.setQuantity(10);\n');
fs.appendFileSync(path, '        itemDTO.setUnitPrice(100.0);\n');
fs.appendFileSync(path, '        testOrderItemDTOs.add(itemDTO);\n');
fs.appendFileSync(path, '\n');
fs.appendFileSync(path, '        testOrderDTO = new OrderDTO();\n');
fs.appendFileSync(path, '        testOrderDTO.setId(1L);\n');
fs.appendFileSync(path, "        testOrderDTO.setOrderNumber('ORD-2024-0001');\n");
fs.appendFileSync(path, "        testOrderDTO.setCustomerName('Test Customer');\n");
fs.appendFileSync(path, '        testOrderDTO.setStatus(Order.Status.PENDING);\n');
fs.appendFileSync(path, '        testOrderDTO.setItems(testOrderItemDTOs);\n');
fs.appendFileSync(path, '    }\n');
console.log('done');