path = r'microservices\\project-root\\core-services\\order-service\\src\\test\\java\\com\\inventory\\orderservice\\service\\impl\\OrderServiceImplTest.java'
Q = chr(34)
lines = []
lines.append('')
lines.append('    @Test')
lines.append('    @DisplayName(' + Q + 'Should throw exception when updating non-existent order' + Q + ')')
lines.append('    void testUpdateOrderNotFound() {')
lines.append('        when(orderRepository.findById(99L)).thenReturn(Optional.empty());')
lines.append('        assertThrows(OrderNotFoundException.class, () -> orderService.updateOrder(99L, testOrderDTO));')
lines.append('    }')
lines.append('')
lines.append('    @Test')
lines.append('    @DisplayName(' + Q + 'Should delete order' + Q + ')')
lines.append('    void testDeleteOrder() {')
lines.append('        when(orderRepository.findById(1L)).thenReturn(Optional.of(testOrder));')
lines.append('        when(orderRepository.save(any(Order.class))).thenAnswer(i -> i.getArgument(0));')
lines.append('        orderService.deleteOrder(1L);')
lines.append('        verify(orderRepository).save(any(Order.class));')
lines.append('    }')
lines.append('')
lines.append('    @Test')
lines.append('    @DisplayName(' + Q + 'Should throw exception when deleting non-existent order' + Q + ')')
lines.append('    void testDeleteOrderNotFound() {')
lines.append('        when(orderRepository.findById(99L)).thenReturn(Optional.empty());')
lines.append('        assertThrows(OrderNotFoundException.class, () -> orderService.deleteOrder(99L));')
lines.append('    }')
lines.append('')
lines.append('    @Test')
lines.append('    @DisplayName(' + Q + 'Should throw exception when inventory deduction fails' + Q + ')')
lines.append('    void testCreateOrderInventoryDeductionFails() {')
lines.append('        when(orderRepository.save(any(Order.class))).thenAnswer(i -> {')
lines.append('            Order o = i.getArgument(0);')
lines.append('            o.setId(1L);')
lines.append('            return o;')
lines.append('        });')
lines.append('        when(inventoryClient.deductStock(any(), any())).thenReturn(False);')
lines.append('        assertThrows(InsufficientInventoryException.class, h -> orderService.createOrder(testOrderDTO));')
lines.append('    }')
lines.append('')
lines.append('    @Test')
lines.append('    @DisplayName(' + Q + 'Should transition from PENDING to PROCESSING' + Q + ')')
lines.append('    void testPendingToProcessing() {')
lines.append('        when(orderRepository.findById(1L)).thenReturn(Optional.of(testOrder));')
lines.append('        when(orderRepository.save(any(Order.class))).thenAnswer(i -> i.getArgument(0));')
lines.append('        OrderDTO result = orderService.updateOrderStatus(1L, Order.Status.PROCESSING);')
lines.append('        assertEquals(Order.Status.PROCESSING, result.getStatus());')
lines.append('    }')
lines.append('')
lines.append('    @Test')
lines.append('    @DisplayName(' + Q + 'Should transition from PENDING to CANCELLED and restore inventory' + Q + ')')
lines.append('    void testPendingToCancelled() {')
lines.append('        testOrder.setStatus(Order.Status.PENDING);')
lines.append('        when(orderRepository.findById(1L)).thenReturn(Optional.of(testOrder));')
lines.append('        when(orderRepository.save(any(Order.class))).thenAnswer(i -> i.getArgument(0));')
lines.append('        when(inventoryClient.restoreStock(any(), any())).thenReturn(True);')
lines.append('        OrderDTO result = orderService.cancelOrder(1L);')
lines.append('        assertEquals(Order.Status.CANCELLED, result.getStatus());')
lines.append('    }')
lines.append('')
lines.append('    @Test')
lines.append('    @DisplayName(' + Q + 'Should transition from PROCESSING to COMPLETED' + Q + ')')
lines.append('    void testProcessingToCompleted() {')
lines.append('        testOrder.setStatus(Order.Status.PROCESSING);')
lines.append('        when(orderRepository.findById(1L)).thenReturn(Optional.of(testOrder));')
lines.append('        when(orderRepository.save(any(Order.class))).thenAnswer(i -> i.getArgument(0));')
lines.append('        OrderDTO result = orderService.updateOrderStatus(1L, Order.Status.COMPLETED);')
lines.append('        assertEquals(Order.Status.COMPLETED, result.getStatus());')
lines.append('    }')
with open(path, 'a', encoding='utf-8') as f:
    f.write('\\n'.join(lines))
print('done')
