with open(path, 'w', encoding='utf-8') as f:
    f.write('@ExtendWith(MockitoExtension.class)\\n')
    f.write('@MockitoSettings(strictness = Strictness.LENIENT)\\n')
    f.write('class OrderServiceImplTest {\\n\\n')
    f.write('    @Mock private IOrderRepository orderRepository;\\n')
    f.write('    @Mock private IOrderItemRepository orderItemRepository;\\n')
    f.write('    @Mock private InventoryClient inventoryClient;\\n')
    f.write('    @Spy private ModelMapper modelMapper = new ModelMapper();\\n')
    f.write('    @InjectMocks private OrderServiceImpl orderService;\\n\\n')
    f.write('    private Order testOrder;\\n')
    f.write('    private OrderDTO testOrderDTO;\\n')
    f.write('    private List<OrderItem> testOrderItems;\\n')
    f.write('    private List<OrderItemDTO> testOrderItemDTOs;\\n\\n')
    f.write('    @BeforeEach\\n')
    f.write('    void setUp() {\\n')
    f.write('        testOrderItems = new ArrayList<>();\\n')
    f.write('        OrderItem item = new OrderItem();\\n')
    f.write('        item.setId(1L);\\n')
    f.write('        item.setProductId(100L);\\n')
    f.write('        item.setProductName(chr(34) + " Test Product\ + chr(34));\\n')
 f.write(' item.setQuantity(10);\\n')
 f.write(' item.setUnitPrice(100.0);\\n')
 f.write(' item.setCreatedAt(LocalDateTime.now());\\n')
 f.write(' testOrderItems.add(item);\\n\\n')
 f.write(' testOrder = new Order();\\n')
 f.write(' testOrder.setId(1L);\\n')
 f.write(' testOrder.setOrderNumber(chr(34) + \ORD-2024-0001\ + chr(34));\\n')
 f.write(' testOrder.setCustomerName(chr(34) + \Test Customer\ + chr(34));\\n')
 f.write(' testOrder.setStatus(Order.Status.PENDING);\\n')
 f.write(' testOrder.setItems(testOrderItems);\\n')
 f.write(' testOrder.setCreatedAt(LocalDateTime.now());\\n')
 f.write(' testOrder.setUpdatedAt(LocalDateTime.now());\\n')
 f.write(' testOrderItems.forEach(i -> i.setOrder(testOrder));\\n\\n')
 f.write(' testOrderItemDTOs = new ArrayList<>();\\n')
 f.write(' OrderItemDTO itemDTO = new OrderItemDTO();\\n')
 f.write(' itemDTO.setProductId(100L);\\n')
 f.write(' itemDTO.setProductName(chr(34) + \Test Product\ + chr(34));\\n')
 f.write(' itemDTO.setQuantity(10);\\n')
 f.write(' itemDTO.setUnitPrice(100.0);\\n')
 f.write(' testOrderItemDTOs.add(itemDTO);\\n\\n')
 f.write(' testOrderDTO = new OrderDTO();\\n')
 f.write(' testOrderDTO.setId(1L);\\n')
 f.write(' testOrderDTO.setOrderNumber(chr(34) + \ORD-2024-0001\ + chr(34));\\n')
 f.write(' testOrderDTO.setCustomerName(chr(34) + \Test Customer\ + chr(34));\\n')
 f.write(' testOrderDTO.setStatus(Order.Status.PENDING);\\n')
 f.write(' testOrderDTO.setItems(testOrderItemDTOs);\\n')
 f.write(' }\\n')
print('done')
